In [47]:
# 2. Classify flower species based on flower morphology (iris dataset)

from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score, recall_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [46]:
# load and explore data
iris = datasets.load_iris()
print(iris.keys())
print(iris.feature_names)
print(iris.data[0:6, :])
print(iris.target_names)
print(iris.target[0:6])

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]
['setosa' 'versicolor' 'virginica']
[0 0 0 0 0 0]


In [44]:
# feature engineering
irisdf = pd.DataFrame(iris.data, columns=iris.feature_names)
irisdf = irisdf[~irisdf.isnull().any(axis=1)]
irisdf.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [53]:
# run grid search cross validation for random forest classifier
X = irisdf.copy()
y = iris.target.copy()

#Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.3, random_state=1, stratify=y)
 
pars = {'n_estimators': range(1, 101), 'min_samples_split': range(2, 11), 'max_samples': range(1, 5)}
rfor = RandomForestClassifier()
clf = GridSearchCV(rfor, pars, scoring='accuracy', cv=5) # use stratified 5-fold cross-validation
clf.fit(X, y)
#clf.predict()
#print(ypred)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'max_samples': range(1, 5),
                         'min_samples_split': range(2, 11),
                         'n_estimators': range(1, 101)})